[package]
name = "ipc-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.190"
serde_derive = "1.0.190"
serde_json = "1.0.107"
tokio = { version = "1.33", features = ["full"] }


[lib]
name = "ipc_client"
path = "src/lib.rs"

[[bin]]
name = "ipc_server"
path = "src/main.rs"